### ISSUE TITLE
Suggestion: Automatically applying settings

### ISSUE THREAD

**Issue by greysonevins** [vtoubiana/TrackMeNot#100]
Could we redesign the Options page to automatically update settings when options are clicked as part of the "redesign ticket"? I keep forgetting to click the "Apply" button at the bottom and it would be nice to have the options update.

I could take this one if we want to proceed.

**Comment by cqx931** [comment]
yes, that's surely what we are after. I have worked on the redesign of options page in #90, though only on the ui. I can push my changes to a new branch, do you want to take it over and start your work from there? @greysonevvins Thanks!

**Comment by greysonevins** [comment]
@cqx931 I can!

**Comment by greysonevins** [comment]
https://github.com/vtoubiana/TrackMeNot/pull/101
@cqx931

**Comment by cqx931** [comment]
verified and merged
