### ISSUE TITLE
Firefox Nightly: search tab is no longer invisible

### ISSUE THREAD

**Issue by groovecoder** [vtoubiana/TrackMeNot#109]
The extension seems to have stopped working in the latest Firefox Nightly, and the background tab for searches is no longer invisible.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/71928/29071845-f02fd52c-7c0a-11e7-8960-644c7c13af9b.png">

Error in the console is:
```
document.defaultView.document.body is null  tmn_search.js:553

sendPageLoaded moz-extension://f72137cf-db93-1641-9685-eeaec518f7ab/tmn_search.js:553:13
	setTMNCurrentURL moz-extension://f72137cf-db93-1641-9685-eeaec518f7ab/tmn_search.js:594:9
	getTMNCurrentURL/< moz-extension://f72137cf-db93-1641-9685-eeaec518f7ab/tmn_search.js:583:13
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:59:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:174:38
	runSafeWithoutClone self-hosted:949:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:353:13
```

**Comment by vtoubiana** [comment]
I am not sure the error has soemething to do with Firefox nightly, might just be the fact that Google removed Instant search so that TMN has to simulate a click on the search button now.

Tab can't be really hidden, the idea was just that they would not get the focus, but they are visible.

**Comment by vtoubiana** [comment]
I think I've fixed the problem in this release: https://github.com/vtoubiana/TrackMeNot/releases/tag/10.0.3

Strangely some object could not be transferred via tabs.runtime.sendMessage, it had to be stringified first. This changed appeared in FF57 it seems.
