### ISSUE TITLE
Not using RSS list, only the zeitgeist

### ISSUE THREAD

**Issue by javenschuetz** [vtoubiana/TrackMeNot#118]
Hello,

In both firefox and brave, the queries do not use my RSS feed list.

...I felt bad about 'complaining' about it, so I actually found a fix for it. I'll open a PR momentarily and link back to this issue in the commit description.

**Comment by javenschuetz** [comment]
Fair enough, I don't have permissions to push a branch for a PR. Would somebody consider this fix in lieu of a real PR?

near line 928 in trackmenot.js, indexOf is evaluating to -1, which is removing the 'rss' element from the typeoffeeds array

} else {
-            typeoffeeds.splice(typeoffeeds.indexOf('dhs'), 1);
+            if (typeoffeeds.indexOf('dhs') !== -1) typeoffeeds.splice(typeoffeeds.indexOf('dhs'), 1);
             TMNQueries.dhs = null;
         }

**Comment by genevera** [comment]
@javenschuetz I just added the if statement you proposed.

**Comment by javenschuetz** [comment]
thanks!

**Comment by genevera** [comment]
@javenschuetz would you mind adding a :+1: to my PR?  I don't know how active the author is and I'd prefer it get merged rather than ppl become dependent on my fork

**Comment by javenschuetz** [comment]
done!

**Comment by vtoubiana** [comment]
I'll try to merge everything this weekend, sorry for the delayed answer.

**Comment by vtoubiana** [comment]
The change have been added to the version that I pushed for Chrome this morning. The other big change is that now it creates a tab to send the queries.

**Comment by genevera** [comment]
cool.  mind closing this? :)
