### ISSUE TITLE
Code for Chrome Extension

### ISSUE THREAD

**Issue by dhananjay92** [vtoubiana/TrackMeNot#35]
I was debugging this bug that I found after installing TMN(0.2.3) from chrome store. _(It doesn't show the log when I click on `show` button. I located the error which is that inside `TRACKMENOT.Options.showLog()`, `localStorage["logs-tmn"]` is `undefined`. )_

But I could not find the code for Chrome extension anywhere! I mean in the code on master doesn't match with the code for TMN 0.2.3 that I installed from Chrome store. My guess is that the code on master is may be for Firefox TMN.

Anyway, so can you please tell me where I can find the code for that extension?

**Comment by vtoubiana** [comment]
Hi,

Thanks for helping. The code is here: https://github.com/vtoubiana/TrackMeNot-Chrome .
Let me know if I can help,

Cheers
