### ISSUE TITLE
Settings not persistent

### ISSUE THREAD

**Issue by LoveIsGrief** [vtoubiana/TrackMeNot#37]
This doesn't seem to happen all the time, but the settings don't seem to stay put. I have configured firefox to delete all my history, except passwords and site preferences, on browser exit. Often when restarting my browser I find TMN to have the default settings and my settings to have been wiped.

The Reddit Enhancement Suite seemed to have a problem with that as well. How are settings stored?

**Comment by vtoubiana** [comment]
Dear Michael,

Thank you for the feedback. TrackMeNot settings are stored with "simple storage" (https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-storage), it's similar to local storage from what I understand. Do you have examples of extensions which does not have the same problem? That'd help us to find a solution.

Best regards,

Vincent

**Comment by LoveIsGrief** [comment]
Hey Vincent,

honestbleeps/Reddit-Enhancement-Suite#1893 seems related but their solution might be using [indexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), which might be overkill for TMN since it doesn't have that many preferences. Possibly [simple-prefs](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-prefs) might be better for TMN's case?

Cheers

**Comment by steph643** [comment]
I get the same problem with the Chrome extension.

**Comment by vtoubiana** [comment]
This should be fixed now. I move everything to localStorage which has some drawbacks but is similarly used by all Web Extension system.
