### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sciunto** [vtoubiana/TrackMeNot#40]
Hi,

I do not see anything about the license (here or on mozilla). Could you specify that please?

Thank you.

**Comment by vtoubiana** [comment]
Hi,

TrackMeNot is licensed under GPL 2.0. The licensed files used to be attached to the extension but I forgot to copy it when we started to use Jetpack (my bad). The licensed is mention in the package.json file.

This will be fixed with next commit.

Thank you

**Comment by sciunto** [comment]
awesome! :)
