### ISSUE TITLE
Buttons not working in the Options panel

### ISSUE THREAD

**Issue by steph643** [vtoubiana/TrackMeNot#45]
I use the Chrome extension. 
The 3 buttons at the top of the Options page ("Help/FAQ*", "Main Site" and "Show Queries") don't work. When clicking on them, nothing happens, except for an error message in the console:

> options.html:1 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by vtoubiana** [comment]
This should be fixed
