### ISSUE TITLE
DHS option seems unavailable

### ISSUE THREAD

**Issue by steph643** [vtoubiana/TrackMeNot#46]
I use the Chrome extension. 
In the Options panel, when I check "Generate queries including keywords monitored by DHS" then click "Apply", the checkbox comes back to unchecked state.

**Comment by vtoubiana** [comment]
I've made a couple of changes on the Chrome version (which will become the only version) and fixed this issue. You can get  these changes from the TMN-Chrome repository.

I'll packaged an update TMN extension soon.
