### ISSUE TITLE
Changes/resets default search engine to Yahoo

### ISSUE THREAD

**Issue by groovecoder** [vtoubiana/TrackMeNot#49]
[As described on AMO](https://addons.mozilla.org/en-US/firefox/addon/trackmenot/reviews/837685/) ...

I installed TrackMeNot, restarted Firefox, and my search engine had changed from DuckDuckGo to Yahoo. I un-installed TrackMeNot, restarted Firefox, and it was still Yahoo. I had to go back into search preferences to change it back to DuckDuckGo.

**Comment by vtoubiana** [comment]
Hi,

You mean that TMN changed your search engine from DuckDuck go to Yahoo!? That's wird, it's not supposed to do that at all. TMN is not supposed interfere with the the default search engine.

I'll look into this.

Best regards,

Vincent

**Comment by groovecoder** [comment]
It happened twice, but it hasn't happened in a long time. I'm not sure what I did before the times that it happened.

**Comment by vtoubiana** [comment]
This should be fixed with the Web Extension version: https://addons.mozilla.org/fr/firefox/addon/trackmenot/#beta-channel

Through the Beta Channel
