### ISSUE TITLE
Add icon for 'mode': tab or stealth

### ISSUE THREAD

**Issue by dhowe** [vtoubiana/TrackMeNot#55]
![image](https://cloud.githubusercontent.com/assets/737638/26484424/99ff1746-4224-11e7-9c1d-b1fb2c50b35e.png)

**Comment by dhowe** [comment]
perhaps also fix resolution of Disable icon

**Comment by cqx931** [comment]
What is tab mode? Is 'stealth' like incognito or privacy mode?

**Comment by dhowe** [comment]
tab-mode uses a browser tab, stealth uses xhr requests

(correct if any thing has changed @vtoubiana)

**Comment by cqx931** [comment]
Where do the current icons coming from? It would be easier for me to match with the style if I could know the source...

**Comment by dhowe** [comment]
I believe I found them originally, back in 2006 (!), probably just from free internet sources...

**Comment by dhowe** [comment]
I had checked in these two a while back, but someone were deleted or not used...

![tab_icon](https://cloud.githubusercontent.com/assets/737638/26756282/1ee16bdc-48d1-11e7-8674-2532b6a28686.png)

![stealth_icon](https://cloud.githubusercontent.com/assets/737638/26756281/1edd93f4-48d1-11e7-9913-d810c200f9fc.png)

we might also try to fix the wide-spacing in the menu

**Comment by dhowe** [comment]
we might also try to fix the wide-spacing in the menu, if it is easy:

![image](https://cloud.githubusercontent.com/assets/737638/26756296/6ca26b5a-48d1-11e7-97b8-
c528d820981c.png)

**Comment by cqx931** [comment]
How about something like this (tried my best to match with the style)
![image](https://cloud.githubusercontent.com/assets/3056154/26762328/df1d9c6c-4972-11e7-908c-ff0c09e95be2.png)

**Comment by dhowe** [comment]
Nice! though it is either tab or stealth, never both...

**Comment by dhowe** [comment]
looks good
