### ISSUE TITLE
Should automatically choose between Firefox & Chrome install buttons

### ISSUE THREAD

**Issue by dhowe** [vtoubiana/TrackMeNot#65]
See AdNauseam code

**Comment by cqx931** [comment]
Changed the install buttons.
The default is showing firefox download button and a download link for chrome below

![image](https://cloud.githubusercontent.com/assets/3056154/26719813/98258c90-47b8-11e7-8dcf-f73878911a80.png)

**Comment by dhowe** [comment]
You mean that on Firefox it appears as above, and on Chrome, the opposite?

**Comment by cqx931** [comment]
yes

**Comment by dhowe** [comment]
I'm not sure we need the bold link underneath -- the common behavior (in mozilla, google, & opera addon stores) only to show the primary choice

**Comment by dhowe** [comment]
Also, we need to figure out how to get web-page changes into the workflow...

Currently, the website is checked in under the 'web' directory, however there is no automated way of pushing these changes live.

@toubiana, we also need to make sure that the web-directory is not being built into the extension itself whenever it is published

**Comment by cqx931** [comment]
It makes sense to show that Trackmenot is also available for other browser except the current one. Otherwise, why does AdNauseam show all three download options at the same time?
Yes, bold primary choice sounds good.

**Comment by dhowe** [comment]
Because he we say it clearly in the text below, so it is OK to just show the active browser...

**Comment by cqx931** [comment]
Ok, so it should be:
1. Only display the primary download link for Firefox and Chrome
2. What other browsers? Still showing both?
