### ISSUE TITLE
Adjust alignment in options

### ISSUE THREAD

**Issue by dhowe** [vtoubiana/TrackMeNot#79]
![image](https://cloud.githubusercontent.com/assets/737638/26772244/daba2f1c-49f6-11e7-8eef-1f58bff5aa4a.png)

fix alignment horizontal alignment above.
and text should be (notice capitalization):

- Enabled
- Use tab to search
- Enable burst-mode

**Comment by dhowe** [comment]
perhaps add this to PR/#78

**Comment by cqx931** [comment]
https://github.com/vtoubiana/TrackMeNot/pull/78/commits/9c8b3334b4051c6c715cdb86f591948a2c76312b fixed
