### ISSUE TITLE
TrackMeNot suddenly displaying a red ERROR message

### ISSUE THREAD

**Issue by Exomancer** [vtoubiana/TrackMeNot#80]
TrackMeNot is suddenly displaying a red ERROR message.  It has been since the June 7th update.

**Comment by greysonevins** [comment]
@Exomancer

**Comment by greysonevins** [comment]
@Exomancer can you give more details on this issue?

Are you building TrackMeNot from github or are you using it from an extension store in a browser?

What browser are you experiencing this on?

What are your query logs reading in the options page?

**Comment by nlienard** [comment]
Same issue, i did a fresh install on FF 55.0.3 and i got Error in Red on the icon.
TMN error when mouse over on the icon.
How to troubleshoot ?
Thanks

**Comment by nlienard** [comment]
Ok after restarting ff, it looks like it works
