### ISSUE TITLE
Query log goals

### ISSUE THREAD

**Issue by dhowe** [vtoubiana/TrackMeNot#81]
The first question we need to answer for the query log is what it is trying to accomplish. There is perhaps an argument that we don't even need it, as the same info is shown in the log itself.

I think that if we decide to keep it, then it needs to be dynamically updating, with new entries at the top.
@vtoubiana -- what are your thoughts? others ?

A separate but related issue is how we show queries in the browser interface itself (#60). Originally they were shown in the status bar, which worked quite well, but that has now gone away. Now they are shown on the badge, which, at least imho, does not work, as they only show one or a few letters. Any thoughts on this?

**Comment by cqx931** [comment]
When I look into the code, 'Show Queries' shows all the queries in storage, which consists of two parts:
1.Keywords from the variable `zeitgeist`
2.RSS queries (by default, fetched from NYT home page)

As far as I understand this, the log and the queries are designed for different goals:
1.The log is more like an activity log for TrackMeNot and, and yes, it would be better if the log can be updated dynamically without refresh.
2.The queries is not the same as the queries column in log, it is not the dynamic searching history but a list of possible queries that TMN is going to use. Also, there seems to be no 'new entries' for me in query log, as it always shows the zeitgeist keywords first, then the rss feed result. The old rss feeds would be replaced by new ones if I change the url.

The queries do get updated when I click 'validate' button, though the way that they are placed in the interface doesn't show any visual hint that these two are related...

For me, the query log itself works fine, but the two issues below need to be improved:
1. Dynamically update the log
2. Move RSS Feed under 'show queries' and show relationship between these two with text/design

**Comment by dhowe** [comment]
closed in favor of redesign ticket
