### ISSUE TITLE
Updated FAQ and DevFAQ

### ISSUE THREAD

**Issue by dhowe** [vtoubiana/TrackMeNot#82]
see existing AdNauseam FAQ (dhowe/TrackMeNot:gh-pages branch) -- add any missing entries

add DevFAQ info to Wiki: https://github.com/vtoubiana/TrackMeNot/wiki

FAQ (faq.html): 

1. where does TrackMeNot get its queries from ?
2. what is the difference between stealth and tab modes?
3. what is burst mode?
4. how does the query set 'evolve' over time ?
5. how do i add a new search engine ?
6. what does 'keywords monitored by DHS' mean ?
7. what is the blacklist ?

DevFAQ (wiki):

1. How to download/build ?
2. How to view debugging messages ?
2. How to test on various platforms (Firefox, Chrome, Opera, Firefox-mobile, Edge?)
2. How to do release testing

<br>

**Comment by greysonevins** [comment]
https://github.com/greysonevins/TrackMeNot-Wiki

**Comment by dhowe** [comment]
> see existing AdNauseam FAQ (dhowe/TrackMeNot:gh-pages branch) -- add any missing entries

the FAQ exists as part of the website, as described above: https://github.com/dhowe/TrackMeNot/blob/gh-pages/faq.html

Please migrate your changes there and do a regular PR

**Comment by greysonevins** [comment]
@dhowe PR made for FAQ.html page

**Comment by greysonevins** [comment]
https://github.com/greysonevins/TrackMeNot-Wiki/ @dhowe @cqx931
