### ISSUE TITLE
Unable to add new search engine

### ISSUE THREAD

**Issue by cqx931** [vtoubiana/TrackMeNot#93]
![image](https://user-images.githubusercontent.com/3056154/27623390-d660cd7a-5c0e-11e7-8e2e-c35985f81a76.png)

**Comment by dhowe** [comment]
Thats not a very clarifying error message -- is there documentation somewhere on the format for adding a search engine (in the FAQ perhaps?)

**Comment by cqx931** [comment]
Ah, I see... yes, I need to provide a link as below `https://duckduckgo.com/?q=trackmenot&t=h_&ia=web` to add the engine. 

How about just showing the current helping text instead?

> To add the engine url, search 'trackmenot' (without the quotes) on the engine you want to add, and copy/paste(There is a typo in the current text) the search url in the URL text box bellow.

**Comment by dhowe** [comment]
you mean in the error?

**Comment by vtoubiana** [comment]
Thanks for fixing this
